#!/bin/bash
# https://t.me/gemilangkinasih

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotbackup)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"

IP=$(cat /etc/xray/ipvps)
domain=$(cat /etc/xray/domain)
date=$(date +"%d-%B-%Y")
time=$(date +"%H:%M WIB")
DOMAIN_PART=$(cut -d '.' -f1 /etc/xray/domain)

clear
echo "Mohon Menunggu, Proses Backup Sedang Berlangsung!"
cd /root
rm -rf /root/backup
mkdir -p /root/backup/ > /dev/null 2>&1
mkdir -p /root/backup/xray/ > /dev/null 2>&1
mkdir -p /root/backup/html/ > /dev/null 2>&1
mkdir -p /root/backup/limit/ssh/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vmess/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vless/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/trojan/ip > /dev/null 2>&1
mkdir -p /root/backup/quota/vmess > /dev/null 2>&1
mkdir -p /root/backup/quota/vless > /dev/null 2>&1
mkdir -p /root/backup/quota/trojan > /dev/null 2>&1
mkdir -p /root/backup/quotax/vmess > /dev/null 2>&1
mkdir -p /root/backup/quotax/vless > /dev/null 2>&1
mkdir -p /root/backup/quotax/trojan > /dev/null 2>&1
cp /etc/passwd /root/backup/ 
cp /etc/group /root/backup/ 
cp /etc/shadow /root/backup/ 
cp /etc/gshadow /root/backup/ 
cp -r /etc/kyt/limit/ssh/ip/* /root/backup/limit/ssh/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vmess/ip/* /root/backup/limit/vmess/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vless/ip/* /root/backup/limit/vless/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/trojan/ip/* /root/backup/limit/trojan/ip > /dev/null 2>&1
cp -r /etc/vmess/* /root/backup/quota/vmess > /dev/null 2>&1
cp -r /etc/vless/* /root/backup/quota/vless > /dev/null 2>&1
cp -r /etc/trojan/* /root/backup/quota/trojan > /dev/null 2>&1
cp -r /etc/limit/vmess/* /root/backup/quotax/vmess > /dev/null 2>&1
cp -r /etc/limit/vless/* /root/backup/quotax/vless > /dev/null 2>&1
cp -r /etc/limit/trojan/* /root/backup/quotax/trojan > /dev/null 2>&1
cp /etc/xray/*.json /root/backup/xray/
cp /var/www/html/*.txt /root/backup/html/ > /dev/null 2>&1
cp -r /etc/ssh/.ssh.db /root/backup/.ssh.db > /dev/null 2>&1
cp -r /etc/vmess/.vmess.db /root/backup/.vmess.db > /dev/null 2>&1
cp -r /etc/vless/.vless.db /root/backup/.vless.db > /dev/null 2>&1 
cp -r /etc/trojan/.trojan.db /root/backup/.trojan.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.ssh.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.vmess.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.vless.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.trojan.db > /dev/null 2>&1
cd /root
zip -r $DOMAIN_PART.zip backup > /dev/null 2>&1

response=$(curl -s -X POST -F "file=@/root/$DOMAIN_PART.zip" https://gmvpn.my.id/backup/upload.php)
url=$(echo "$response" | jq -r '.url')

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
──────────────────────
Backup Vps Server Success
──────────────────────
<code>Host :</code> <code>$domain</code>
<code>IP   :</code> <code>$IP</code>
<code>Date :</code> <code>$date</code>
<code>Time :</code> <code>$time</code>
──────────────────────
Link Backup :
$url
────────────────────── "
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
rm -r /root/backup
rm -rf /root/$DOMAIN_PART.zip

clear
echo -e "
──────────────────────
Backup Vps Server Success
──────────────────────
Host  : $domain
IP    : $IP
Date  : $date
Time  : $time
──────────────────────
Link Backup :
$url
──────────────────────
"
echo ""
