#!/bin/bash
# https://t.me/gemilangkinasih

CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotbackup)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
domain=$(cat /etc/xray/domain)
date=$(date +"%Y-%m-%d")
clear
cd /root
rm -rf /root/backup
mkdir -p /root/backup/ > /dev/null 2>&1
mkdir -p /root/backup/xray/ > /dev/null 2>&1
mkdir -p /root/backup/html/ > /dev/null 2>&1
mkdir -p /root/backup/limit/ssh/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vmess/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vless/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/trojan/ip > /dev/null 2>&1
mkdir -p /root/backup/quota/vmess > /dev/null 2>&1
mkdir -p /root/backup/quota/vless > /dev/null 2>&1
mkdir -p /root/backup/quota/trojan > /dev/null 2>&1
mkdir -p /root/backup/quotax/vmess > /dev/null 2>&1
mkdir -p /root/backup/quotax/vless > /dev/null 2>&1
mkdir -p /root/backup/quotax/trojan > /dev/null 2>&1
cp /etc/passwd /root/backup/ 
cp /etc/group /root/backup/ 
cp /etc/shadow /root/backup/ 
cp /etc/gshadow /root/backup/ 
cp -r /etc/kyt/limit/ssh/ip/* /root/backup/limit/ssh/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vmess/ip/* /root/backup/limit/vmess/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vless/ip/* /root/backup/limit/vless/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/trojan/ip/* /root/backup/limit/trojan/ip > /dev/null 2>&1
cp -r /etc/vmess/* /root/backup/quota/vmess > /dev/null 2>&1
cp -r /etc/vless/* /root/backup/quota/vless > /dev/null 2>&1
cp -r /etc/trojan/* /root/backup/quota/trojan > /dev/null 2>&1
cp -r /etc/limit/vmess/* /root/backup/quotax/vmess > /dev/null 2>&1
cp -r /etc/limit/vless/* /root/backup/quotax/vless > /dev/null 2>&1
cp -r /etc/limit/trojan/* /root/backup/quotax/trojan > /dev/null 2>&1
cp /etc/xray/*.json /root/backup/xray/
cp /var/www/html/*.txt /root/backup/html/ > /dev/null 2>&1
cp -r /etc/ssh/.ssh.db /root/backup/.ssh.db > /dev/null 2>&1
cp -r /etc/vmess/.vmess.db /root/backup/.vmess.db > /dev/null 2>&1
cp -r /etc/vless/.vless.db /root/backup/.vless.db > /dev/null 2>&1 
cp -r /etc/trojan/.trojan.db /root/backup/.trojan.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.ssh.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.vmess.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.vless.db > /dev/null 2>&1
sed -i '/^#&/d' /root/backup/.trojan.db > /dev/null 2>&1
cd /root
zip -r $IP-$date.zip backup >/dev/null 2>&1
TEXT="
──────────────────────
Backup VPS Server Berhasil
──────────────────────
<code>Subdomain VPS :</code> <code>$domain</code>
<code>IP Server VPS :</code> <code>$IP</code>
<code>Date ToBackup :</code> <code>$date</code>
────────────────────── "
curl -s --http1.1 --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
curl --http1.1 -F chat_id="$CHATID" -F document=@"$IP-$date.zip" "https://api.telegram.org/bot$KEY/sendDocument"
rm -r backup
rm -r $IP-$date.zip