#!/bin/bash
clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m         PILIH JENIS PROTOKOL XRAY        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
echo "1. VMESS"
echo "2. VLESS"
echo "3. TROJAN"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
read -p "Masukkan pilihan [1-3]: " protocol_choice

# Tentukan tipe protokol berdasarkan pilihan
case $protocol_choice in
    1)
        protocol="vmess"
        ;;
    2)
        protocol="vless"
        ;;
    3)
        protocol="trojan"
        ;;
    *)
        echo "Pilihan tidak valid. Keluar."
        exit 1
        ;;
esac

function con() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 )) KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 )) MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 )) GB"
    fi
}

# Masukkan UUID
read -p "Masukkan UUID: " uuid

if [[ "$protocol" == "vless" ]]; then
    username=$(grep "$uuid" /etc/xray/config.json | uniq | tail -n 2 | head -n 1 | sed -n 's/.*"email" *: *"\([^"]*\)".*/\1/p')
else
    username=$(grep "$uuid" /etc/xray/config.json | uniq | tail -n 2 | head -n 1 | sed -n 's/.*"email": "\([^"]*\)".*/\1/p')
fi

if [[ "$protocol" == "trojan" ]]; then
    protocolx="$protocol-ws"
else
    protocolx="$protocol"
fi

# Ambil informasi dari file konfigurasi Xray
CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotserver)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=$(cat /etc/xray/domain)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
MYIP=$(cat /etc/xray/ipvps)

if [[ -n "$username" ]]; then
    case $protocol in
        "vmess")
            # Generate konfigurasi VMESS
            vmess_tls=$(cat <<EOF
{
  "v": "2",
  "ps": "$username",
  "add": "$domain",
  "port": "443",
  "id": "$uuid",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "$domain",
  "tls": "tls",
  "sni": "$domain"
}
EOF
)

            vmess_ntls=$(cat <<EOF
{
  "v": "2",
  "ps": "$username",
  "add": "$domain",
  "port": "80",
  "id": "$uuid",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "$domain",
  "tls": "none"
}
EOF
)

            vmess_grpc=$(cat <<EOF
{
  "v": "2",
  "ps": "$username",
  "add": "$domain",
  "port": "443",
  "id": "$uuid",
  "aid": "0",
  "net": "grpc",
  "path": "vmess-grpc",
  "type": "none",
  "host": "$domain",
  "tls": "tls",
  "sni": "$domain"
}
EOF
)

            # Encode base64
            vmesslink1="vmess://$(echo "$vmess_tls" | base64 -w 0)"
            vmesslink2="vmess://$(echo "$vmess_ntls" | base64 -w 0)"
            vmesslink3="vmess://$(echo "$vmess_grpc" | base64 -w 0)"
            exp=$(grep -wE "^### $username" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            iplimit=$(cat /etc/kyt/limit/$protocol/ip/$username)
            quotax=$(cat /etc/$protocol/$username)
            quota=$(con "$quotax")
            ;;

        "vless")
            # Generate konfigurasi VLESS
            vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${username}"
            vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws&host=${domain}#${username}"
            vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&authority=${domain}&type=grpc&serviceName=vless-grpc&sni=${domain}#${username}"
            exp=$(grep -wE "^#& $username" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            iplimit=$(cat /etc/kyt/limit/$protocol/ip/$username)
            quotax=$(cat /etc/$protocol/$username)
            quota=$(con "$quotax")
            ;;

        "trojan")
            # Generate konfigurasi TROJAN
            trojanlink1="trojan://${uuid}@${domain}:443?path=/trojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${username}"
            trojanlink2="trojan://${uuid}@${domain}:80?path=/trojan-ws&security=none&host=${domain}&type=ws#${username}"
            trojanlink3="trojan://${uuid}@${domain}:443?mode=gun&security=tls&authority=${domain}&type=grpc&serviceName=trojan-grpc&sni=${domain}#${username}"
            exp=$(grep -wE "^#! $username" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            iplimit=$(cat /etc/kyt/limit/$protocol/ip/$username)
            quotax=$(cat /etc/$protocol/$username)
            quota=$(con "$quotax")
            ;;
    esac

clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m          PILIH JENIS OUTPUT XRAY         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
echo "1. STANDART"
echo "2. TELEGRAM MONOSCAPE"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
read -p "Masukkan pilihan [1-2]: " output_choice

    case $output_choice in
    1)
    clear
    echo "──────────────────────"
    echo "Status Create $protocol Success"
    echo "──────────────────────"
    echo "✧ ISP   : $ISP"
    echo "✧ City  : $CITY"
    echo "──────────────────────"
    echo "✧ Host  : $domain"
    echo "✧ User  : $username"
    echo "✧ UUID  : $uuid"
    echo "✧ Max   : $iplimit IP"
    echo "✧ Quota : $quota"
    echo "✧ Port  : 443, 80"
    echo "✧ Path  : /$protocolx"
    echo "──────────────────────"

    case $protocol in
        "vmess")
            echo "✧ TLS   : $vmesslink1"
            echo "──────────────────────"
            echo "✧ nTLS  : $vmesslink2"
            echo "──────────────────────"
            echo "✧ Grpc  : $vmesslink3"
            ;;
        "vless")
            echo "✧ TLS   : $vlesslink1"
            echo "──────────────────────"
            echo "✧ nTLS  : $vlesslink2"
            echo "──────────────────────"
            echo "✧ Grpc  : $vlesslink3"
            ;;
        "trojan")
            echo "✧ WS    : $trojanlink1"
            echo "──────────────────────"
            echo "✧ Grpc  : $trojanlink3"
            ;;
    esac

    echo "──────────────────────"
    echo "✧ Exp   : $exp"
    echo "──────────────────────"
        ;;
    2)
    clear
    echo "──────────────────────"
    echo "Status Create $protocol Success"
    echo "──────────────────────"
    echo "\`✧ ISP   :\` \`$ISP\`"
    echo "\`✧ City  :\` \`$CITY\`"
    echo "──────────────────────"
    echo "\`✧ Host  :\` \`$domain\`"
    echo "\`✧ User  :\` \`$username\`"
    echo "\`✧ UUID  :\` \`$uuid\`"
    echo "\`✧ Max   :\` \`$iplimit IP\`"
    echo "\`✧ Quota :\` \`$quota\`"
    echo "\`✧ Port  :\` \`443, 80\`"
    echo "\`✧ Path  :\` \`/$protocolx\`"
    echo "──────────────────────"

    case $protocol in
        "vmess")
            echo "\`✧ TLS   :\` \`$vmesslink1\`"
            echo "──────────────────────"
            echo "\`✧ nTLS  :\` \`$vmesslink2\`"
            echo "──────────────────────"
            echo "\`✧ Grpc  :\` \`$vmesslink3\`"
            ;;
        "vless")
            echo "\`✧ TLS   :\` \`$vlesslink1\`"
            echo "──────────────────────"
            echo "\`✧ nTLS  :\` \`$vlesslink2\`"
            echo "──────────────────────"
            echo "\`✧ Grpc  :\` \`$vlesslink3\`"
            ;;
        "trojan")
            echo "\`✧ WS    :\` \`$trojanlink1\`"
            echo "──────────────────────"
            echo "\`✧ Grpc  :\` \`$trojanlink3\`"
            ;;
    esac

    echo "──────────────────────"
    echo "\`✧ Exp   :\` \`$exp\`"
    echo "──────────────────────"
        ;;
    *)
        echo "Pilihan tidak valid. Keluar."
        exit 1
        ;;
    esac
else
    echo "UUID tidak ditemukan"
fi
