#!/bin/bash
# https://t.me/gemilangkinasih

# Getting
CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotserver)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

read -p "Input Username Account : " User

if ! grep -qiw "$User" /etc/passwd; then
    echo -e "Username tidak ada."
    exit 0
fi

STATUS=$(passwd -S "$User" | awk '{print $2}')
if [ "$STATUS" == "L" ]; then
echo -e "Username locked."
exit 0 
fi

CONFIG_FILE="/etc/zivpn/config.json"
TMP_FILE="/etc/zivpn/config.tmp"
current_exp=$(chage -l $User | grep "Account expires" | awk -F": " '{print $2}')
formatted_date=$(date -d "$current_exp" +"%Y-%m-%d")
userdel $User > /dev/null 2>&1
jq --arg pw "$User" '.auth.config -= [$pw]' "$CONFIG_FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$CONFIG_FILE"
sed -i "/^### $User/d" /etc/ssh/.ssh.db
rm -r /var/www/html/ssh-Trial-"$User".txt > /dev/null 2>&1
rm -r /var/www/html/ssh-"$User".txt > /dev/null 2>&1
systemctl restart ssh >/dev/null 2>&1
systemctl restart sshd >/dev/null 2>&1

TEXT="
──────────────────────
Delete Account SSHWS Success
──────────────────────
<code>✧ Host  :</code> <code>$domain</code>
<code>✧ User  :</code> <code>$User</code>
<code>✧ Exp   :</code> <code>$formatted_date</code>
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
atq | awk '{print $1}' | while read job; do at -c "$job" | grep -q "autobackupbot" && atrm "$job"; done &> /dev/null
echo "autobackupbot" | at now + 30 minutes &> /dev/null

echo "$User"
echo "$formatted_date"
