#!/bin/bash
# https://t.me/gemilangkinasih

# Getting
CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotserver)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

read -p "Input Username Account : " User
read -p "Day Extend : " Days

if ! grep -qiw "$User" /etc/passwd; then
    echo -e "Username tidak ada."
    exit 0
fi

Pass=$(grep -w "^### $User" /etc/ssh/.ssh.db | awk '{print $4}')
current_exp=$(chage -l $User | grep "Account expires" | awk -F": " '{print $2}')
formatted_date=$(date -d "$current_exp" +"%Y-%m-%d")
if [[ "$current_exp" == "never" ]]; then
  Today=$(date +%s)
else
  Today=$(date -d "$current_exp" +%s)
fi
Days_Detailed=$(( ($Days+1) * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expirationx=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y-%m-%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
passwd -u $User >/dev/null
usermod -e  $Expiration $User >/dev/null
egrep "^$User" /etc/passwd >/dev/null
echo -e "$Pass\n$Pass\n"| passwd $User &> /dev/null
sed -i "/### $User/c\### $User $Expirationx $Pass" /etc/ssh/.ssh.db

TEXT="
──────────────────────
Extend Account SSHWS Success
──────────────────────
<code>✧ Host  :</code> <code>$domain</code>
<code>✧ User  :</code> <code>$User</code>
<code>✧ Plus  :</code> <code>$Days Days</code>
<code>✧ Exp   :</code> <code>$Expirationx</code>
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
atq | awk '{print $1}' | while read job; do at -c "$job" | grep -q "autobackupbot" && atrm "$job"; done &> /dev/null
echo "autobackupbot" | at now + 30 minutes &> /dev/null

echo "$User"
echo "$Days Days"
echo "$formatted_date"
echo "$Expirationx"
