#!/bin/bash
# https://t.me/gemilangkinasih

CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebotserver)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
  
read -p "Username Info : " user
read -p "Expired Day   : " masaaktif

if ! grep -qiw "$user" /etc/xray/config.json; then
    echo -e "Username tidak ada."
    exit 0
fi

exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)

if (( masaaktif >= 30 )); then
    echo "0" > "/etc/limit/vmess/${user}"
fi

now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $masaaktif))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
uuid=$(grep -w "^### $user $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)
sed -i "/### $user/c\### $user $exp4" /etc/xray/config.json
sed -i "/### $user/c\### $user $exp4 $uuid" /etc/vmess/.vmess.db
systemctl restart xray > /dev/null 2>&1

TEXT="
──────────────────────
Extend Account VMESS Success
──────────────────────
<code>✧ Host  :</code> <code>$domain</code>
<code>✧ User  :</code> <code>$user</code>
<code>✧ Plus  :</code> <code>$masaaktif Days</code>
<code>✧ Exp   :</code> <code>$exp4</code>
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
atq | awk '{print $1}' | while read job; do at -c "$job" | grep -q "autobackupbot" && atrm "$job"; done &> /dev/null
echo "autobackupbot" | at now + 30 minutes &> /dev/null

echo -e "$user"
echo -e "$masaaktif Days"
echo -e "$exp"
echo -e "$exp4"